name: Assemble Smali
on:
 workflow_dispatch
permissions:
 contents: write
jobs:
 smali:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Aliucord
    uses: actions/checkout@v4
    with:
     repository: "Aliucord/Aliucord"
     ref: "main"
     path: "src"
   - name: Checkout smali
    uses: actions/checkout@v4
    with:
     ref: "smali"
     path: "smali"
   - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v4
   - name: Assemble smali
    run: |
     cd $GITHUB_WORKSPACE/src
     chmod +x ./gradlew
     ./gradlew :patches:disassembleWithPatches
     cp -R -T $GITHUB_WORKSPACE/smali/smali/. $GITHUB_WORKSPACE/src/patches/smali/
     chmod +x ./gradlew
     ./gradlew :patches:writePatches :patches:testPatches
   - name: Push smali
    run: |
     cd $GITHUB_WORKSPACE/src
     git remote remove origin
     git remote add origin https://github.com/Archimedes9500/Aliucord
     git config --local user.email "actions@github.com"
     git config --local user.name "GitHub Actions"
     git add .
     git commit -m "Smali $GITHUB_SHA" || exit 0 # do not error if nothing to commit
     git push --force origin main
