name: Create Smali
on:
 workflow_dispatch
permissions:
 contents: write
jobs:
 smali:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
    uses: actions/checkout@v4
    with:
     path: "src"
   - name: Checkout smali
    uses: actions/checkout@v4
    with:
     ref: "smali"
     path: "smali"
   - name: Setup Gradle
    uses: gradle/actions/setup-gradle@v4
   - name: Generate Smali
    run: |
     cd $GITHUB_WORKSPACE/src
     rm -rf $GITHUB_WORKSPACE/smali/original-smali/
     rm -rf $GITHUB_WORKSPACE/smali/smali/
     chmod +x gradlew
     ./gradlew :patches:disassembleWithPatches
     cp -R -T /home/runner/work/Aliucord/Aliucord/src/patches/smali/. $GITHUB_WORKSPACE/smali/original-smali/
     cp -R -T /home/runner/work/Aliucord/Aliucord/src/patches/smali/. $GITHUB_WORKSPACE/smali/smali/
   - name: Push smali
    run: |
     cd $GITHUB_WORKSPACE/smali
     git config --local user.email "actions@github.com"
     git config --local user.name "GitHub Actions"
     git add .
     git commit -m "Smali $GITHUB_SHA" || exit 0 # do not error if nothing to commit
     git push
